Fix jq

diff --git a/megadown b/megadown
--- a/megadown
+++ b/megadown
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-VERSION="1.9.39"
+VERSION="1.9.45"
 
 HERE=$(dirname "$0")
 SCRIPT=$(readlink -f "$0")
-HELPERS="$HERE/helpers.py"
 BASH_MIN_VER="3"
-PYTHON_MIN_VER="2.6"
 
 MEGA_API_URL="https://g.api.mega.co.nz"
 OPENSSL_AES_CTR_128_DEC="openssl enc -d -aes-128-ctr"
@@ -27,19 +25,19 @@ function showError {
 function showHelp {
 	echo -e "\nmegadown $VERSION - https://github.com/tonikelope/megadown"
 	echo -e "\ncli downloader for mega.nz and megacrypter"
-	echo -e "\nSingle url mode:           megadown <'URL'> [OPTION]...\n"
+	echo -e "\nSingle url mode:           megadown [OPTION]... 'URL'\n"
 	echo -e "\tOptions:"
 	echo -e "\t-o,\t--output FILE_NAME    Store file with this name."
 	echo -e "\t-s,\t--speed SPEED         Download speed limit (integer values: 500B, K, 2M)."
 	echo -e "\t-p,\t--password PASSWORD   Password for MegaCrypter links."
 	echo -e "\t-q,\t--quiet               Quiet mode."
-	echo -e "\t-m,\t--metadata            Prints file metadata and exits. (File name is base64 encoded)."
-	echo -e "\n\nMulti url mode:          megadown <-l URL_LIST_FILE> [OPTION]...\n"
+	echo -e "\t-m,\t--metadata            Prints file metadata in JSON format and exits."
+	echo -e "\n\nMulti url mode:          megadown [OPTION]... -l|--list FILE\n"
 	echo -e "\tOptions:"
 	echo -e "\t-s,\t--speed SPEED         Download speed limit (integer values: 500B, 500K, 2M)."
 	echo -e "\t-p,\t--password PASSWORD   Password for MegaCrypter links (same for every link in a list)."
 	echo -e "\t-q,\t--quiet               Quiet mode."
-	echo -e "\t-m,\t--metadata            Prints file metadata and exits. (File name is base64 encoded)."
+	echo -e "\t-m,\t--metadata            Prints file metadata in JSON format and exits."
 	echo -e "\tFile line format:          URL [optional_file_name]\n"
 }
 
@@ -58,7 +56,7 @@ function check_deps {
 		dep_error=1
 	fi
 
-	for i in openssl python pv; do
+	for i in openssl pv jq; do
 
 		if [ -z "$(command -v "$i" 2>&1)" ]; then
 
@@ -84,20 +82,14 @@ function check_deps {
 
 					done
 				;;
-
-				python)
-
-					if [[ "$(python --version 2>&1 | grep -o -E '[0-9]\.[0-9]')" < "$PYTHON_MIN_VER" ]]; then
-
-						echo "python >= ${PYTHON_MIN_VER} is required"
-						dep_error=1
-
-					fi
-				;;
 			esac
 		fi
 
 	done
+
+	if [ -z "$(command -v python 2>&1)" ]; then
+		echo "WARNING: python is required for MegaCrypter password protected links and it's not installed."
+	fi
 
 	if [[ "$(echo -n "$BASH_VERSION" | grep -o -E "[0-9]+" | head -n1)" < "$BASH_MIN_VER" ]]; then
 		echo "bash >= ${BASH_MIN_VER} is required"
@@ -107,6 +99,13 @@ function check_deps {
 	if [ $dep_error -ne 0 ]; then
 		showError "ERROR: there are dependencies not present!"
 	fi
+}
+
+
+# 2:url
+function urldecode {
+
+	: "${*//+/ }"; echo -e "${_//%/\\x}"; 
 }
 
 # 1:b64_encoded_string
@@ -166,14 +165,14 @@ function get_mc_link_info {
 	fi
 
 	if [ $(echo $info_link | grep '"error"') ]; then
-		local error_code=$($HELPERS json_param "$info_link" error)
+		local error_code=$(echo "$info_link" | jq -r .error)
 		echo -e "MEGACRYPTER ERROR $error_code"
 		return 1
 	fi
 
-	local expire=$($HELPERS json_param "$info_link" expire)
+	local expire=$(echo "$info_link" | jq -r .expire)
 
-	if [ "$expire" != "0" ]; then
+	if [ "$expire" != "false" ]; then
 
 		IFS='#' read -a array <<< "$expire"
 
@@ -182,19 +181,19 @@ function get_mc_link_info {
 		local no_exp_token="$expire"
 	fi
 
-	local file_name=$(echo -n $($HELPERS json_param "$info_link" name) | base64 -w 0 -i 2>/dev/null)
+	local file_name=$(echo "$info_link" | jq -r .name | base64 -w 0 -i 2>/dev/null)
 
-	local path=$(echo -n $($HELPERS json_param "$info_link" path))
+	local path=$(echo "$info_link" | jq -r .path)
 
-	if [ "$path" != "0" ]; then
+	if [ "$path" != "false" ]; then
 		path=$(echo -n "$path" | base64 -w 0 -i 2>/dev/null)
 	fi
 
-	local mc_pass=$($HELPERS json_param "$info_link" pass)
+	local mc_pass=$(echo "$info_link" | jq -r .pass)
 
-	local file_size=$($HELPERS json_param "$info_link" size)
+	local file_size=$(echo "$info_link" | jq -r .size)
 
-	local key=$($HELPERS json_param "$info_link" key)
+	local key=$(echo "$info_link" | jq -r .key)
 
 	echo -n "${file_name}@${path}@${file_size}@${mc_pass}@${key}@${no_exp_token}"
 }
@@ -238,6 +237,12 @@ function format_file_size {
 	echo -ne "$file_size_f"
 }
 
+# 1:password 2:salt 3:iterations
+function mc_pbkdf2 {
+
+	echo -e "import sys,hashlib,base64\nprint(base64.b64encode(hashlib.pbkdf2_hmac('sha256', b'${1}', base64.b64decode(b'${2}'), ${3})).decode())" | python
+}
+
 # 1:mc_pass_info 2:pass_to_check
 function mc_pass_check {
 
@@ -251,9 +256,7 @@ function mc_pass_check {
 
 	local iv=${array[3]}
 
-	local password=$(echo -n "$2" | base64 -w 0 -i 2>/dev/null)
-
-	local mc_pass_hash=$($HELPERS pbkdf2 "$salt" "$password" $((2**$iter_log2)))
+	local mc_pass_hash=$(mc_pbkdf2 "$password" "$salt" $((2**$iter_log2)))
 
 	mc_pass_hash=$(echo -n "$mc_pass_hash" | base64 -d -i 2>/dev/null | od -v -An -t x1 | tr -d '\n ')
 
@@ -302,13 +305,7 @@ if [ -z "$1" ]; then
 	exit 1
 fi
 
-p1=$(trim "$1")
-
-if [[ "$p1" =~ ^http ]] || [[ "$p1" =~ ^mega:// ]]; then
-	link="$p1"
-fi
-
-eval set -- "$(getopt -o "l:p:k:o:s:qm" -l "list:,password:,key:,output:,speed:,quiet,metadata" -- "$@")"
+eval set -- "$(getopt -o "l:p:k:o:s:qm" -l "list:,password:,key:,output:,speed:,quiet,metadata" -n ${0} -- "$@")"
 
 while true; do
 	case "$1" in
@@ -326,6 +323,12 @@ while true; do
 			exit 1;;
 	esac
 done
+
+p1=$(trim $(urldecode "$1"))
+
+if [[ "$p1" =~ ^http ]] || [[ "$p1" =~ ^mega:// ]]; then
+	link="$p1"
+fi
 
 if [ -z "$link" ]; then
 
@@ -450,9 +453,9 @@ if [ $(echo -n "$link" | grep -E -o 'mega(\.co)?\.nz') ]; then
 		showError "MEGA ERROR $(echo -n "$mega_res_json" | grep -E -o '\-[0-9]+')"
 	fi
 
-	file_size=$($HELPERS json_param "$mega_res_json" s)
+	file_size=$(echo "$mega_res_json" | jq -r .[0].s)
 
-	at=$($HELPERS json_param "$mega_res_json" at)
+	at=$(echo "$mega_res_json" | jq -r .[0].at)
 
 	hex_key=$(hrk2hk "$hex_raw_key")
 
@@ -463,9 +466,14 @@ if [ $(echo -n "$link" | grep -E -o 'mega(\.co)?\.nz') ]; then
 	fi
 
 	if [ -z "$output" ]; then
-		file_name=$($HELPERS json_param "$(echo -n "$at_dec_json" | grep -E -o '\{.+\}')" n)
+		file_name=$(echo -n "$at_dec_json" | grep -E -o '\{.+\}' | jq -r .n)
 	else
 		file_name="$output"
+	fi
+
+	if [ $metadata ]; then
+		echo "{\"file_name\" : \"${file_name}\", \"file_size\" : ${file_size}}"
+		exit 0
 	fi
 
 	check_file_exists "$file_name" "$file_size" "$(format_file_size "$file_size")"
@@ -484,12 +492,12 @@ if [ $(echo -n "$link" | grep -E -o 'mega(\.co)?\.nz') ]; then
 		showError "Oooops, something went bad. EXIT CODE (${download_exit_code})"
 	fi
 
-	dl_temp_url=$($HELPERS json_param "$mega_res_json" g)
+	dl_temp_url=$(echo "$mega_res_json" | jq -r .[0].g)
 else
 
 	#MEGACRYPTER LINK
 
-	MC_API_URL=$(echo -n "$1" | grep -i -E -o 'https?://[^/]+')"/api"
+	MC_API_URL=$(echo -n "$link" | grep -i -E -o 'https?://[^/]+')"/api"
 
 	md5=$(echo -n "$link" | $OPENSSL_MD5 | grep -E -o '[0-9a-f]{32}')
 
@@ -516,7 +524,7 @@ else
 
 	path=${array[1]}
 
-	if [ "$path" != "0" ]; then
+	if [ "$path" != "false" ]; then
 		path=$(echo -n "$path" | base64 -d -i 2>/dev/null)
 	fi
 
@@ -528,17 +536,14 @@ else
 
 	no_exp_token=${array[5]}
 
-	if [ "$path" != "0" ] && [ "$path" != "" ]; then
+	if [ "$mc_pass" != "false" ]; then
 
-		if [ ! -d "$path" ]; then
+		if [ -z "$(command -v python 2>&1)" ]; then
 
-			mkdir -p "$path"
+			echo "ERROR: python is required for MegaCrypter password protected links and it's not installed."
+			exit 1
+
 		fi
-
-		file_name="${path}${file_name}"
-	fi
-
-	if [ "$mc_pass" != "0" ]; then
 
 		echo -ne "\nLink is password protected. "
 
@@ -556,7 +561,7 @@ else
 
 			pass_hash=$(mc_pass_check "$mc_pass" "$pass")
 
-			until [ "$pass_hash" != "0" ]; do
+			until [ "$pass_hash" != "false" ]; do
 				read -e -p "Wrong password! Try again: " pass
 				pass_hash=$(mc_pass_check "$mc_pass" "$pass")
 			done
@@ -579,6 +584,21 @@ else
 		hex_raw_key=$(echo -n $(urlb64_to_b64 "$key") | base64 -d -i 2>/dev/null | od -v -An -t x1 | tr -d '\n ')
 	fi
 
+	if [ $metadata ]; then
+		echo "{\"file_name\" : \"${file_name}\", \"file_size\" : ${file_size}}"
+		exit 0
+	fi
+
+	if [ "$path" != "false" ] && [ "$path" != "" ]; then
+
+		if [ ! -d "$path" ]; then
+
+			mkdir -p "$path"
+		fi
+
+		file_name="${path}${file_name}"
+	fi
+
 	check_file_exists "$file_name" "$file_size" "$(format_file_size "$file_size")" "$md5"
 
 	hex_key=$(hrk2hk "$hex_raw_key")
@@ -593,24 +613,19 @@ else
 
 	if [ $(echo $dl_link | grep '"error"') ]; then
 
-		error_code=$($HELPERS json_param "$dl_link" error)
+		error_code=$(echo "$dl_link" | jq -r .error)
 
 		showError "MEGACRYPTER ERROR $error_code"
 	fi
 
-	dl_temp_url=$($HELPERS json_param "$dl_link" url)
+	dl_temp_url=$(echo "$dl_link" | jq -r .url)
 
-	if [ "$mc_pass" != "0" ]; then
+	if [ "$mc_pass" != "false" ]; then
 
-		iv=$(echo -n $($HELPERS json_param "$dl_link" pass) | base64 -d -i 2>/dev/null | od -v -An -t x1 | tr -d '\n ')
+		iv=$(echo "$dl_link" | jq -r .pass | base64 -d -i 2>/dev/null | od -v -An -t x1 | tr -d '\n ')
 
 		dl_temp_url=$(echo -n "$dl_temp_url" | $OPENSSL_AES_CBC_256_DEC -K "$pass_hash" -iv "$iv")
 	fi
-fi
-
-if [ $metadata ]; then
-	echo -n $(echo -n "$file_name" | base64 -i)"|${file_size}"
-	exit 0
 fi
 
 if [ -z "$speed" ]; then
